default:
  watchpaths:
    styles:
      - ./src/**/*.scss
    reload:
      - ./**/*.html

  styles:
    sources:
      - ./src/styles/**/*.scss
    concat: flexboxgrid.min.css
    dest: ./dest/
    options:
      sourcemap: true
      style: compressed

  example:
    sources:
      - ./src/example.scss
    concat: example.min.css
    dest: ./
    options:
      sourcemap: false
      style: compressed

  browsersync:
    open: false
    port: 3000
    server:
      baseDir: './'
