default:
  watchpaths:
    styles:
      - ./src/**/*.scss
      - ./example/**/*.scss
    reload:
      - ./**/*.html

  styles:
    sources:
      - ./src/styles/**/*.scss
    concat: flex-blocks.min.css
    dest: ./dist/
    options:
      sourcemap: true
      style: compressed

  example:
    sources:
      - ./example/**/*.scss
    concat: example.min.css
    dest: ./example
    options:
      sourcemap: false
      style: compressed

  browsersync:
    open: false
    port: 3000
    server:
      baseDir: './example'
